let world = { "height":10,
 "layers":[
        {
         "data":[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2],
         "height":10,
         "name":"Capa de Patrones 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tileheight":32,
 "tilesets":[
        {
         "columns":1,
         "firstgid":1,
         "image":"_CRATEBOY 2007-2014\/_ART\/Brick Wall\/wallside.png",
         "imageheight":32,
         "imagewidth":32,
         "margin":0,
         "name":"wallside",
         "spacing":0,
         "terrains":[
                {
                 "name":"Nuevo Terreno",
                 "tile":-1
                }],
         "tilecount":1,
         "tileheight":32,
         "tiles":
            {
             "0":
                {
                 "objectgroup":
                    {
                     "draworder":"index",
                     "height":0,
                     "name":"",
                     "objects":[],
                     "opacity":1,
                     "type":"objectgroup",
                     "visible":false,
                     "width":0,
                     "x":0,
                     "y":0
                    }
                }
            },
         "tilewidth":32
        }, 
        {
         "columns":1,
         "firstgid":2,
         "image":"_CRATEBOY 2007-2014\/_ART\/Brick Wall\/marbletile.png",
         "imageheight":32,
         "imagewidth":32,
         "margin":0,
         "name":"marbletile",
         "spacing":0,
         "tilecount":1,
         "tileheight":32,
         "tiles":
            {
             "0":
                {
                 "objectgroup":
                    {
                     "draworder":"index",
                     "height":0,
                     "name":"",
                     "objects":[
                            {
                             "height":0,
                             "id":1,
                             "name":"",
                             "polygon":[
                                    {
                                     "x":0,
                                     "y":0
                                    }, 
                                    {
                                     "x":30,
                                     "y":0
                                    }, 
                                    {
                                     "x":29.3333333333333,
                                     "y":30.6666666666667
                                    }, 
                                    {
                                     "x":0.666666666666667,
                                     "y":30.6666666666667
                                    }],
                             "rotation":11,
                             "type":"",
                             "visible":true,
                             "width":12,
                             "x":4.33,
                             "y":-0.67
                            }],
                     "opacity":1,
                     "type":"objectgroup",
                     "visible":true,
                     "width":0,
                     "x":0,
                     "y":0
                    }
                }
            },
         "tilewidth":32
        }, 
        {
         "columns":1,
         "firstgid":3,
         "image":"_CRATEBOY 2007-2014\/_ART\/Brick Wall\/walltop.png",
         "imageheight":32,
         "imagewidth":32,
         "margin":0,
         "name":"walltop",
         "spacing":0,
         "tilecount":1,
         "tileheight":32,
         "tilewidth":32
        }],
 "tilewidth":32,
 "version":1,
 "width":10
}